declare module '*.mp3';
declare module '*.mp4';
declare module 'react-page-scroller';
declare module 'react-reveal/Zoom';
declare module 'react-reveal/Fade';
declare module 'react-reveal/Bounce';
declare module 'react-reveal/Roll';
declare module 'react-reveal/Flip';
declare module 'react-avatar-editor';
